log_level = "state:info,*:error"
db_backend = "leveldb"
fast_sync = true
moniker = "207.154.203.177"
proxy_app = "tcp://127.0.0.1:46658"

[consensus]
create_empty_blocks_interval = 1

[rpc]
laddr = "tcp://0.0.0.0:46657"

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "104.131.86.166:46656,178.62.46.14:46656,146.185.173.132:46656"
max_num_peers = 500
