# This is a TOML config file
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "YOURNAME"
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[consensus]
create_empty_blocks_interval = 60

[tx_index]
index_all_tags = true

[p2p]
max_num_peers = 300
pex = true
laddr = "tcp://0.0.0.0:46656"
# DNS works here.
seeds = "165.227.246.236:46656,67.207.78.91:46656,207.154.217.39:46656,139.162.19.186:46656,35.225.5.124:46656,35.226.159.196:46656,peer.gaia-3003.valid.st:5653,169.229.198.105:46656,gaia-3003-a.mycosmosvalidator.com:46656,gaia-3003-b.mycosmosvalidator.com:46656,gaia-3003-c.mycosmosvalidator.com:46656,172.31.28.156:46656,54.90.40.94:46656,18.197.23.227:46656,104.237.6.136:46656,148.76.42.147:46656,197.49.108.149:46656,cosmos01.validator.tokenpla.net:46656,cosmos02.validator.tokenpla.net:46656,cosmos03.validator.tokenpla.net:46656"
